# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MessageWin import Ui_MainMessageWIndow
import requests

link = "http://duski.pythonanywhere.com"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.Mainwin = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 180)
        MainWindow.setFixedSize(556,180)
        MainWindow.setStyleSheet("background-color:rgb(27, 54, 81);\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.maddress_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.maddress_2.setGeometry(QtCore.QRect(120, 30, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.maddress_2.setFont(font)
        self.maddress_2.setAutoFillBackground(False)
        self.maddress_2.setStyleSheet("background-color: rgb(66, 119, 204);\n"
                                      "border:0px;")
        self.maddress_2.setText("")
        self.maddress_2.setObjectName("maddress_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 29, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Signup = QtWidgets.QPushButton(self.centralwidget)
        self.Signup.setGeometry(QtCore.QRect(10, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(16)
        self.Signup.setFont(font)
        self.Signup.setAutoFillBackground(False)
        self.Signup.setStyleSheet("QPushButton\n"
                                  "{\n"
                                  "background-color : rgb(48, 95, 143);\n"
                                  "border-style: outset;\n"
                                  "border-width: 1px;\n"
                                  "border-radius: 1px;\n"
                                  "border-color:black;\n"
                                  "}\n"
                                  "QPushButton::pressed\n"
                                  "{\n"
                                  "background-color : rgb(85, 170, 255);\n"
                                  "}\n"
                                  "\n"
                                  "")
        self.Signup.setCheckable(False)
        self.Signup.setChecked(False)
        self.Signup.setDefault(True)
        self.Signup.setFlat(False)
        self.Signup.setObjectName("Signup")
        self.maddress_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.maddress_3.setGeometry(QtCore.QRect(120, 77, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(16)
        self.maddress_3.setFont(font)
        self.maddress_3.setAutoFillBackground(False)
        self.maddress_3.setStyleSheet("background-color: rgb(66, 119, 204);\n"
                                      "border:0px;")
        self.maddress_3.setText("")
        self.maddress_3.setObjectName("maddress_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(14, 77, 107, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(190, 130, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code Light")
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setAutoFillBackground(False)
        self.login.setStyleSheet("QPushButton\n"
                                 "{\n"
                                 "background-color : rgb(48, 95, 143);\n"
                                 "border-style: outset;\n"
                                 "border-width: 1px;\n"
                                 "border-radius: 1px;\n"
                                 "border-color:black;\n"
                                 "}\n"
                                 "QPushButton::pressed\n"
                                 "{\n"
                                 "background-color : rgb(85, 170, 255);\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.login.setCheckable(False)
        self.login.setChecked(False)
        self.login.setDefault(True)
        self.login.setFlat(False)
        self.login.setObjectName("login")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Signup.clicked.connect(lambda:self.account(0))
        self.login.clicked.connect(lambda:self.account(1))
        self.maddress_3.setEchoMode(QtWidgets.QLineEdit.Password)   
    def account(self, method):
        if method == 0:
                r = requests.post(f"{link}/signup",data={'nm':self.maddress_2.text(),'ps':self.maddress_3.text()})
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowTitle("Info")
                msg.setText(r.content.decode())
                msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
                msg.exec_()
        else:
                r = requests.post(f"{link}/login",data={'nm':self.maddress_2.text(),'ps':self.maddress_3.text()})
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information)
                msg.setWindowTitle("Info")
                msg.setText(r.content.decode())
                msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
                msg.exec_()
                if "Logged in" in r.content.decode():
                    self.new_win()
    def new_win(self):
        self.messageWindow = QtWidgets.QMainWindow()   
        self.ui = Ui_MainMessageWIndow()
        self.ui.username = self.maddress_2.text()
        self.ui.password = self.maddress_3.text()
        self.ui.setupUi(self.messageWindow)   
        self.messageWindow.show() 
        self.Mainwin.close() 
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.Signup.setText(_translate("MainWindow", "Signup"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.login.setText(_translate("MainWindow", "login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
